### ISSUE TITLE
Just a Simple User's Comment

### ISSUE THREAD

**Issue by mtrontz-the-dev** [ekfuhrmann/badge-generator#65]
I just want to say that, after reading through your description of the main project and this generator, I am very grateful for your inclusion and descriptive experience of opentype.js. It is the little things such as those that could really become a huge headache for a developer down the line. And for unexperienced developers, such as myself, those kinds of issues could really crush morale, yet from my experience of reading other projects, they mostly give the "view from above" description, and leave the rest for us to figure out. Anyways, all I wanted to say was that it was really cool for you to include such a thorough solution to what could have been a huge frustration. You guys deserve way more stars than you currently have, (I contributed the second star on this repo), but my expectation is that they will soon come. Keep up the great work!

**Comment by ekfuhrmann** [comment]
I really appreciate the kind words!

All projects seem to come with their own challenges, no matter how well prepared you feel going into it. I learned a lot going through the exercise of figuring out how to generate these badges to the fidelity we expected and ultimately that makes the whole project rewarding in the end. I can't tell you how excited I was each time I had a breakthrough (almost always leading to another challenge), but it's those _wins_ that make development worthwhile to me.

I'm happy to hear you appreciated reading the repo as to be honest most of that README was an outlet to express the process a bit. There is something cathartic about being able to put pain to paper, so to speak, and express the frustrations outwardly. I actually made a fun little **[FigJam](https://www.figma.com/file/IxwJhOKu9neq6RMVRXSHT2/For-The-Badge-Generator?node-id=0%3A1)** for my team while doing this to just document that journey and express myself which the README is derived from.

Anyway, I did just want to again thank you for the kind words. It means a lot that you took the time to reach out create this issue just to say something kind. You brought a smile to this developers face!
